[package]
name = "fhs-compliance-lambda"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
home-energy-model-wrapper-fhs = { path = ".." }
anyhow = "1.0.100"
lambda_http = "1.0.1"
parking_lot = "0.12.5"
serde_json = "1.0.145"
tokio = { version = "1", features = ["macros"] }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
